export const projects = [
	{
		num: "01",
		category: "Fullstack Chat App",
		title: "Talkiffy",
		description:
			"A production-style real-time chat platform built with the MERN stack focused on scalable real-time communication, modern React architecture, secure authentication, media handling, and responsive user experience.",
		stack: [
			{ name: "React" },
			{ name: "Node.js" },
			{ name: "Express" },
			{ name: "MongoDB" },
			{ name: "Socket.IO" },
			{ name: "Cloudinary" },
			{ name: "Framer Motion" },
		],
		highlights: [
			"Private Chats",
			"Group Chats",
			"Socket.IO Real-Time",
			"Online Presence",
			"Push Notifications",
			"JWT Authentication",
			"HTTP-Only Cookies",
			"Optimistic UI",
			"Cache Reconciliation",
			"Multi-Device Sync",
			"Seen / Delivered",
			"Message Reactions",
			"Reply System",
			"Message Search",
			"Unread Counts",
			"Avatar Uploads",
			"Image Uploads",
			"Sharp Image Optimization",
			"Cloudinary Storage",
			"TanStack Query",
			"Context API",
			"Custom Hooks",
			"Responsive UI",
			"Framer Motion",
		],
		image: "/talkiffy.png",
		video: "/videos/talkiffy-demo.mp4",
		live: "https://talkiffy.vercel.app",
		github: "https://github.com/alidadashzadeh/TALKIFFY-V2",
	},
	{
		num: "02",
		category: "Food Ordering App",
		title: "Pizzarium",
		description:
			"A pizza ordering platform with signature pizzas, custom pizza builder, drinks, cart drawer, secure checkout flow, Supabase backend, authentication and a clean responsive UI.",
		stack: [
			{ name: "Next.js" },
			{ name: "TypeScript" },
			{ name: "Stripe" },
			{ name: "Supabase" },
			{ name: "React Query" },
			{ name: "Tailwind" },
		],
		highlights: [
			"SSR Menu Pages (SEO Optimized)",
			"Stripe Checkout + Webhook Flow",
			"Server-Side Price Validation",
			"Supabase Auth (SSR Cookies)",
			"Custom Pizza Builder",
			"Dynamic Pizza Image Generation",
			"Cart Drawer UX",
			"Order State Management",
			"React Query Cache Sync",
			"Protected Routes Middleware",
			"Profile & Avatar Upload",
			"Dark Mode Support",
			"Order History System",
			"Clean Component Architecture",
		],
		image: "/pizzarium.png",
		video: "/videos/pizzarium-demo.mp4",
		live: "https://pizzarium.vercel.app/",
		github: "https://github.com/alidadashzadeh/PIZZARIUM-2",
	},
	{
		num: "03",
		category: "Portfolio Website",
		title: "Personal Portfolio",
		description:
			"A responsive portfolio website built with Next.js, Tailwind CSS, Framer Motion, and modern UI components to showcase projects, resume, services, and contact information.",
		stack: [
			{ name: "Next.js" },
			{ name: "Tailwind" },
			{ name: "Framer Motion" },
		],
		highlights: [
			"Next.js App Router Architecture",
			"Server-Side Rendering (SSR)",
			"Framer Motion Animations",
			"Responsive Mobile-First Design",
			"Reusable Component System",
			"Optimized Image & Asset Loading",
			"SEO-Friendly Structure",
			"Interactive Project Showcase",
			"Video Preview Integration",
			"Deployed on Vercel",
			"Clean UI with shadcn/ui",
		],
		image: "/portfolio.jpg",
		video: "",
		live: "",
		github: "https://github.com/alidadashzadeh/portfolio",
	},
];
